### ISSUE TITLE
[Feature]: Curp Storage

### ISSUE THREAD

**Issue by markcty** [datenlord/Xline#181]
### Description about the feature

# Curp Storage

## When to persist?

1. propose: before returning, should flush cmd to disk if it is added to spec pool
2. append_entries: before returning, should flush persisted state(if changed) and new entries to disk
3. vote: before returning, should flush persisted state(if changed) to disk
4. tick_election: should flush persisted state(if term updated and voted for itself) to disk
5. GC: When a cmd is removed from spec pool(after execution, or in gc task), update disk file. However, we don't need to wait for the disk operation, because even if it fails, it won't hurt correctness.

## API

```Rust
/// Curp storage api
#[async_trait::async_trait]
pub(super) trait StorageApi {
    /// Command
    type Command: Command;
    /// Error
    type Error: std::error::Error;
    /// Flush persisted state to disk
    async fn flush_persisted_state(
        &self,
        term: u64,
        voted_for: Option<ServerId>,
    ) -> Result<(), Self::Error>;
    /// Flush log entries to disk
    async fn flush_log_entries(
        &self,
        entries: Vec<LogEntry<Self::Command>>,
    ) -> Result<(), Self::Error>;
    /// Flush a new cmd to on-disk spec pool
    async fn spec_pool_add_cmd(&self, cmd: Arc<Self::Command>) -> Result<(), Self::Error>;
    /// Flush cmds to be deleted on on-disk spec pool
    /// Since removing cmds from spec pool doesn't hurt correctness, we can buffer it
    async fn spec_pool_remove_cmds(&self, cmd: Vec<Arc<Self::Command>>) -> Result<(), Self::Error>;
}
```

## Implementations

There are currently two feasible solutions:

1. Use a WAL(write-ahead-log) like etcd

   Pros:

   * Possibly better performance
   * Fewer dependencies

   Cons:

   * It takes time to develop a correct and high-performance WAL from scratch

2. Use RocksDB

   Pros:

   Cons:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phoenix500526** [comment]
The pros and cons of using a storage engine, like RocksDB:
* Pros:
    * The coding workload can be reduced to a great extent, and the storage engine that has been verified in industry-productive environments will perform better in terms of stability and correctness.
    * There will be more experience to learn from in future tuning, which will also help to promote this project.
* Cons: 
    * Add some additional dependencies and take time to learn how to use a storage engine, like rocksdb. However, the cost of learning how to use a storage engine is relatively low compared to the cost of writing our own WAL implementation. 
    
By the way, a mature storage engine may not be much slower than writing files directly in that they are usually optimized for some concrete scenarios, such as batch processing.

**Comment by rogercloud** [comment]
1. Why should we store the speculative cmd to the disk as it's just a temporary state? So does the GC.
2. Why is ticking a good point to flush disk?

**Comment by markcty** [comment]
Update:

We don't need to persist spec commands since we only need to guarantee that the system works when the majority of servers are still alive. In addition, there is no need to make sure the entries are flushed to disk before returning.

```Rust
/// Curp storage api
#[async_trait::async_trait]
pub(super) trait StorageApi {
    /// Command
    type Command: Command;
    /// Error
    type Error: std::error::Error;
    /// Flush persisted state to disk
    async fn update_persisted_state(
        &self,
        term: u64,
        voted_for: Option<ServerId>,
    ) -> Result<(), Self::Error>;
    /// Flush log entries to disk
    async fn append_log_entries(
        &self,
        entries: Vec<LogEntry<Self::Command>>,
    ) -> Result<(), Self::Error>;
}
```

**Comment by markcty** [comment]
close #184
