### ISSUE TITLE
[Feature]: Curp log compaction

### ISSUE THREAD

**Issue by markcty** [datenlord/Xline#216]
### Description about the feature

Currently, all log entries will stay in memory and disk forever. We need to recycle memory and disk space by compacting these log entires. Ideally, all log entries that have been applied to the state machine are longer needed and therefore can be compacted. However, in case of laggy network, we should reserve some number of entries on each node. In addition, the compaction cost for memory is different from disk. Therefore, there should be two independent compaction strategies, one for memory, one for disk.

### For memory`
Compaction for log entries in memory is easy. We can replace the `entries: Vec<LogEntry<C>>` in `log.rs` with a `VecDeque` of fixed size(say, 5000). Old entries will be popped out when new entires are added.

### For disk
Since I/O operations are expensive and disk space is less likely to be used up as fast as memory, we should not frequently trigger compaction for log entries on disk. We can set a timer to periodically check the number of log entries on disk. If the number exceeds, say 10k, we can use `delete_range` to remove old ones. And the operation is purely async and will not block our curp server.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rogercloud** [comment]
For memory and disk, we should check the entries' states before dropping them. And would you please add the recovery related change after applying log compaction?

**Comment by markcty** [comment]
> For memory and disk, we should check the entries' states before dropping them. And would you please add the recovery related change after applying log compaction?

For memory, we need to check if indexes of entries to be moved are smaller than `last_applied`. For disk, there is no need for checking I believe.

And log entry compaction will have nothing to do with recovery, I guess?

**Comment by rogercloud** [comment]
After using log compaction, followers may try to get the log entries that have been compacted, then the snapshot is sent instead. Is the scenario above the side effect we should care? I guess there are other small side effects.

**Comment by markcty** [comment]
Another possible side effect might be that on restarting a node, we will retain only a fixed number of entries in memory, not all.
