### ISSUE TITLE
Refactor: refactor the dependencies of lease server

### ISSUE THREAD

**Issue by Phoenix500526** [datenlord/Xline#251]
Currently, there is a confusion of dependencies between several components in our lease server. Their dependencies look like this:
![image](https://user-images.githubusercontent.com/9337239/235289043-c22dc7d3-bddc-4e09-a078-5a687bb7396a.png)

I plan to refactor our lease server. This refactoring can be split into two steps:
1. Remove the dependency from `LeaseStoreBackend` to `State`. The main duty of the `State` is to check whether the current node is a leader or not. This is a kind of business logic, and `LeaseStoreBackend` shouldn't be responsible for that while the `LeaseServer` should.
2. Merge the `LeaseStore` and the `LeaseStoreBackend` together. Their definitions look like this:
```Rust
/// Lease store
#[derive(Debug)]
pub(crate) struct LeaseStore<DB>
where
    DB: StorageApi,
{
    /// Lease store Backend
    inner: Arc<LeaseStoreBackend<DB>>,
}

/// Lease store inner
#[derive(Debug)]
struct LeaseStoreBackend<DB>
where
    DB: StorageApi,
{
    /// lease collection
    lease_collection: Arc<LeaseCollection>,
    /// Db to store lease
    db: Arc<DB>,
    /// Key to revision index
    index: Arc<Index>,
    /// Current node is leader or not
    state: Arc<State>,
    /// Revision
    revision: Arc<RevisionNumber>,
    /// Header generator
    header_gen: Arc<HeaderGenerator>,
    /// KV update sender
    kv_update_tx: mpsc::Sender<(i64, Vec<Event>)>,
}
```
There is no point to define a `LeaseStoreBackend` here. We can inline the `LeaseStoreBackend` into the `LeaseStore`. In doing so, we can make our dependencies in the lease_server crystal clear. After refactoring, the dependencies should look like this:
![image](https://user-images.githubusercontent.com/9337239/235289089-b9329608-689e-4712-82b7-e61a84d65187.png)

**Comment by Phoenix500526** [comment]
@rogercloud  @themanforfree

**Comment by Phoenix500526** [comment]
# Requirements

## What are the requirements of LeaseStore for State

When the `LeaseStore` executes the after_sync phase of a `LeaseGrantRequest`, it needs to know whether the current server is a leader or not.

## What are the requirements of LeaseServer for State

1. `revoke_expired_leases_task` is a single background task. It's responsible for finding all the expired leases periodically,  and revoking them when the current server is a leader.

2. `lease_keep_alive` is responsible for renewing a lease, it will generate stream responses continually if the current server is a leader. Otherwise, it will redirect this request to the leader server.

3. `lease_time_to_live` is responsible for looking up the relevant lease information. Only can a leader find such an information, it will redirect this request to the leader server if the current server is not a leader.

## Key requirements
From the information mentioned above, there are two core requirements:
1. Check whether the current server is a leader. 
2. Get the current leader of the cluster, and provides a notification mechanism if it cannot be determined.

# Solution

We can define a `LeaderChange` trait and expose it to the outside users. The user should implement this trait. And the curp will call back this trait when the leadership changes.

Here is the `LeaderChange` trait definition:
```Rust
pub trait LeaderChange {
    fn update_leader(&self, id: Option<String>);
}
```

From the xline server side, we can define a `State` structure to implement this trait. And the `State` looks like:
```Rust
pub struct State {
    /// the current server id
    id: String,    
    /// Leader info
    leader_info: RwLock<LeaderInfo>
    /// members url
    members: HashMap<String, String>,
    
}

struct LeaderInfo {
    /// Leader server id
    leader_id: Option<String>,
    /// notifiers
    notifiers: VecDeque<Arc<Event>>
}

impl LeaderChange for State {
    fn update_leader(&self, id: Option<String>) {
        self.leader_info.map_write(|info| {
            info.leader_id = id;
            info.notifiers.drain(..).for_each(|event| event.notify(usize::MAX));
        });
    }
}

impl State {
    pub fn is_leader(&self) -> bool {
        self.leader_info.map_read(|info| {
            if let Some(id) = info.leader_id {
                id == self.id
            } else {
                false
            }
        })
    }

    pub fn leader_address(&self) -> Option<&String> {
        self.leader_info.map_read(|info| {
            if let Some(id) = info.leader_id {
                let addr = self.members.get(id);
                assert!(addr.is_some(), "{id} address not found in members")
                addr
            } else {
                None
            }
        })
        
    }

    pub fn insert_notifier(&self, event: Arc<Event>) {
        self.leader_info.map_write(|info| {
            assert!(info.leader_id.is_none(), "Should not insert a notifier into notifiers when leader_id is Some");
            info.notifiers.push_back(event);
        })
    }

}
```

# Note

Currently, `LeaseStore` rely on `State` to get whether the current node is a leader or not when executing the `after_sync` phase of `LeaseGrantRequest`.Same as the `LeaseStore`, the `LeaseServer` on a follower server needs to redirect to a leader one when processing some requests, like `keep_alive`. Therefore, it relies on `State` too. Although both the `LeaseServer` and the `LeaseStore` depend on `State`, it would be okay in that there isn't any dependencies cycle between them. After refactoring, the dependencies between them would look like:
![image](https://github.com/datenlord/Xline/assets/9337239/643caba8-c789-46c8-8b9f-8fbd39709ba7)

**Comment by Phoenix500526** [comment]
@rogercloud @themanforfree @bsbds

**Comment by rogercloud** [comment]
LGTM

**Comment by Phoenix500526** [comment]
As the focus between `LeaseStore` and `LeaseServer` is different, `LeaseStore` is concerned about whether the current node is the leader, while `LeaseServer` is interested in both whether the current node is the leader and what is the address of the current cluster leader, we can abstract a `LeaderInfo`, which represents the leader information of the cluster. `LeaseServer` can check whether the current node is a leader through `LeaseStore`, and also get the leader information of the cluster through `LeaderInfo` when it is not a leader. In doing so, we can refine the granularity of the dependencies between `LeaseServer` and `LeaseStore`. 

Here is the modified dependency diagram:
![image](https://github.com/datenlord/Xline/assets/9337239/5f1f7180-e538-4c5b-b88c-54a82ef77789)

The new `LeaderChange` trait definition:
```Rust
/// Callback when the leadership changes
#[cfg_attr(test, automock)]
pub trait LeaderChange: Send + Sync + std::fmt::Debug {
    /// will be invoked when the current server is a leader
    fn on_leader(&self);

    /// will be invoked when the current server is not a leader
    fn on_follower(&self);

    /// will be invoked when the current leader change
    fn update_leader(&self, id: Option<String>);
}
```
Definitions of `State` and `LeaderInfo`
```Rust
// cluster leader information
#[derive(Debug)]
pub(super) struct LeaderInfo {
    /// Leader informattion inner structure
    inner: RwLock<LeaderInfoInner>,
}

/// Leader information inner structure
#[derive(Default, Debug)]
struct LeaderInfoInner {
    /// The current leader id
    id: Option<String>,
    /// Notifiers
    notifiers: VecDeque<Arc<Event>>,
    /// Address of all members
    members: HashMap<String, String>,
}

impl LeaderInfo {
    /// Get leader address
    pub(super) fn get_leader_address(&self) -> Option<String> {
        self.inner.map_read(|inner| {
            if let Some(ref leader_id) = inner.id {
                let addr = inner.members.get(leader_id).cloned();
                assert!(addr.is_some(), "Not such leader id({leader_id}) in members");
                addr
            } else {
                None
            }
        })
    }

    /// Register a event, and it will be notify when the leader id update
    pub(super) fn insert_notifier(&self, notifier: Arc<Event>) {
        self.inner
            .map_write(|mut inner| inner.notifiers.push_back(notifier));
    }

    /// Update leader info
    fn update_leader(&self, new_leader_id: Option<String>) {
        self.inner.map_write(|mut inner| {
            match inner.id {
                None => {
                    if new_leader_id.is_some() {
                        inner.id = new_leader_id;
                        inner.notifiers.drain(..).for_each(|event| event.notify(usize::MAX));
                    }
                },
                Some(ref old_leader) => {
                    if let Some(ref new_leader) = new_leader_id {
                        assert!(inner.notifiers.is_empty(), "notifiers must be empty when leader id change from {old_leader} to {new_leader}");
                        if old_leader != new_leader {
                            inner.id = new_leader_id;
                        }
                    } else {
                        inner.id = new_leader_id;
                    }
                }
            }
        });
    }
}

/// State of current node
#[derive(Debug)]
pub(crate) struct State<DB: StorageApi> {
    /// leader information structure
    leader_info: Arc<LeaderInfo>,
    /// lease storage
    lease_storage: Arc<LeaseStore<DB>>,
}

impl<DB: StorageApi> LeaderChange for State<DB> {
    fn on_leader(&self) {
        self.lease_storage.promote(Duration::from_secs(1)); // TODO: extend should be election timeout
    }

    fn on_follower(&self) {
        self.lease_storage.demote();
    }

    fn update_leader(&self, id: Option<String>) {
        self.leader_info.update_leader(id);
    }
}
```

**Comment by Phoenix500526** [comment]
@rogercloud

**Comment by rogercloud** [comment]
This change makes the lease server simpler as the leadership-change notification goto the storage directly, but not via lease server.

**Comment by rogercloud** [comment]
I recommend to share the leader information between "inner client", the client inside a server, and the server itself. In this way, the client knows the latest leader info, which is updated by the server heartbeat. For the outside the client the leader info is self-contained, shared with no one.
