### ISSUE TITLE
[DOC]: Task of etcd api

### ISSUE THREAD

**Issue by liangyuanpeng** [datenlord/Xline#271]
### Description about the feature

The roadmap say ` Support all major ETCD APIs at v0.1 ~ v0.2`, it would be great list the all of support API.

Just like :

- [x] Get xxx
- [ ] Put xxxx
- ...

A suggestion is  let it exist on README or alone doc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phoenix500526** [comment]
Thank you for your suggestion. Currently, all of the support APIs can be viewed in our [VALIDATION_REPORT](https://github.com/datenlord/Xline/blob/master/VALIDATION_REPORT.md) doc. I'll update this doc and add a link in our README doc.

**Comment by Kylemclean11** [comment]
> ### Description about the feature
> The roadmap say ` Support all major ETCD APIs at v0.1 ~ v0.2`, it would be great list the all of support API.
> 
> Just like :
> 
> * [x]  Get xxx
> * [ ]  Put xxxx
> * ...
> 
> A suggestion is let it exist on README or alone doc.
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

https://github.com/datenlord/Xline/issues/271#issue-1708466311
