### ISSUE TITLE
[DOC]:  Where is the script for  compatibility tests

### ISSUE THREAD

**Issue by liangyuanpeng** [datenlord/Xline#272]
### Description about the feature

As links say `All the compatibility tests are running via etcdctl` , but not provide script for it, it would be great if link to the script and explain for how to run it.

https://github.com/datenlord/Xline/blob/1e206e6ebb95a66b4fa01d558d94a29557b84829/VALIDATION_REPORT.md#L3-L4

# Try to find it

Seems like it is https://github.com/datenlord/Xline/tree/master/scripts/validation_test.sh

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phoenix500526** [comment]
Yes, it is.  I'll add more information about how to run the validation test in our QUICK_START.md. Currently, you can also read our [validation.yml](https://github.com/datenlord/Xline/blob/master/.github/workflows/validation.yml) for more defails.
