### ISSUE TITLE
[Question]:  About Roadmap of Provide clients implementing in different languages, like go, python

### ISSUE THREAD

**Issue by liangyuanpeng** [datenlord/Xline#273]
### Description about the feature

Xline is Etcd compatible API. So what's mean other language sdk?   The Xline SDK? and what's the Xline SDK?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phoenix500526** [comment]
@rogercloud

**Comment by rogercloud** [comment]
The Xline is Etcd compatible, which means Etcd client can talk to xline server directly. For better performance, we provide a Xline specific client SDK, which runs the CURP protocol client side logic. Currently this SDK is only in Rust lang, and we plan to extend the SDK to other languages, such as go and python (not determined).

**Comment by liangyuanpeng** [comment]
Thanks for your quickly reply and it would be great if we can provide they in README or some doc.

**Comment by rogercloud** [comment]
> Thanks for your quickly reply and it would be great if we can provide they in README or some doc.

Good advice, we will add it later.

**Comment by Kylemclean11** [comment]
```javascript

```
