### ISSUE TITLE
[Refactor]: Combine curp common test utils

### ISSUE THREAD

**Issue by bsbds** [datenlord/Xline#290]
Currently in `curp/test_utils` and `curp/tests/common`, there are quite amount of code serve the same purpose. The first one is used for unit tests and the latter one is used for integration tests. I think we should combine them to reduce duplication.

I plan to refactor the code to use a single set of tests utils. After the refactor the curp should expose the test utils in public API, and can be used in both internal integration tests and madsim simulation tests.

**Comment by bsbds** [comment]
In the previous design, was there any reason for not using the curp/test_utils for integration tests? @markcty

**Comment by markcty** [comment]
Well, `curp/test_utils` is simply not visible to the integration tests. You could try moving the test_utils to an independent crate. But it might seem a little weird? Also, their might be circular dependency(I am not sure).

**Comment by bsbds** [comment]
> Well, `curp/test_utils` is simply not visible to the integration tests. You could try moving the test_utils to an independent crate. But it might seem a little weird? Also, their might be circular dependency(I am not sure).

I mean just make the `curp/test_utils` public accessible, no need for a new crate.

**Comment by markcty** [comment]
I think they have a cfg![test], meaning that even you make them public available, they can't be accessed by integration tests.

**Comment by bsbds** [comment]
How about remove the `cfg![test]` and make them public with `#[doc(hidden)]`, so users will not use them in the public crate api.

**Comment by markcty** [comment]
> How about remove the `cfg![test]` and make them public with `#[doc(hidden)]`, so users will not use them in the public crate api.

I guess even with `doc hidden`, users will still be able to access these test interface? Also, these test code will be compiled in release mode, which can enlarge the binary size.

**Comment by bsbds** [comment]
> > How about remove the `cfg![test]` and make them public with `#[doc(hidden)]`, so users will not use them in the public crate api.
> 
> I guess even with `doc hidden`, users will still be able to access these test interface? Also, these test code will be compiled in release mode, which can enlarge the binary size.

Indeed, the users will be able to access the interface because it is a public module, there should be a comment to acknowledge to users why they are there. As for the latter problem, the compiler will optimize unused code, so it shouldn't be an issue.

I have decided to put them in a separate crate, though. To avoid circular dependency, the main crate can put the util crate under [dev-dependencies] then the deps will not propagate.

And finally, thanks for the reply! Your response has been really helpful.

**Comment by bsbds** [comment]
The original plan was to let `curp-test-utils` depends on `curp`, and `curp` dev-depends on `curp-test-utils`. However, that will not work because curp's unit tests will also depends on `curp-test-utils`, which will actually results in an circular dependencies.

![1](https://github.com/datenlord/Xline/assets/69835502/bbda4a32-b7ee-4378-a39b-a7d6f94aa4e1)

To resolve this issue, the `curp-tests-utils` should not depends on curp. Therefore, we extract curp's public trait definitions to a new crate `curp-external-api`. Now, `curp-tests-utils` only needs the dependency of the trait API crate.

![2](https://github.com/datenlord/Xline/assets/69835502/e4ab61cc-9480-4d4a-bf2f-a67778d885ce)
