### ISSUE TITLE
[Feature]:  Relaese Container Image 

### ISSUE THREAD

**Issue by liangyuanpeng** [datenlord/Xline#325]
### Description about the feature

It would be great if we can release container image of Xline, I have find that docker image from https://hub.docker.com/r/datenlord/xline/tags and seems like it's not active.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liangyuanpeng** [comment]
Actually, i'm try to deploy Xline for kube-apiserver and container image of Xline is the first step.  :)

**Comment by Phoenix500526** [comment]
Thanks for your contribution. We'll upload it asap. We add it to our ci process in pr #326.

**Comment by themanforfree** [comment]
The v0.4.1 xline image has been uploaded

**Comment by liangyuanpeng** [comment]
Thanks for your quickly reply. It's still working for me.

# Can not be run with xline-linux-amd64

Just got the error of : `Error: No such file or directory (os error 2)`

## Reproduce

1. wget https://github.com/datenlord/Xline/releases/download/v0.4.1/xline-linux-amd64
2. chmod +x xline-linux-amd64
3. ./xline-linux-amd64


# Can not run with image of `datenlord/xline:v0.4.1`

```shell
lan@lan:~$ docker run -it -d --name xline datenlord/xline:v0.4.1
d2e98f1fb096b7133b72cb52947005f2d044cfebb240f6bb055811310260e0b0
lan@lan:~$ docker logs xline
Error: No such file or directory (os error 2)
```

**Comment by Phoenix500526** [comment]
That's because you are missing some start-up options. You can use `xline --help` for more details. FYI, `https://github.com/datenlord/Xline/blob/master/scripts/quick_start.sh` and `https://github.com/datenlord/Xline/blob/master/QUICK_START.md` would help.
