### ISSUE TITLE
[Bug]: CI clippy fails

### ISSUE THREAD

**Issue by bsbds** [datenlord/Xline#336]
### Description about the bug

The master branch has been failing to pass Cargo clippy recently. The cause of this issue is that the new version of `tracing` crate introduced the clippy lint `clippy::let_with_type_underscore`, which is not supported by current toolchain of the project. We should consider update the toolchain version to keep up these new features.

Ref: https://github.com/tokio-rs/tracing/releases/tag/tracing-attributes-0.1.25

![20230621_09h28m53s_grim](https://github.com/datenlord/Xline/assets/69835502/23ee3d92-970a-4ca4-8130-6406ea99f673)

### Version

0.4.1 (Default)

### Relevant log output

```shell
error: unknown lint: `clippy::let_with_type_underscore`
   --> curp/src/client.rs:116:10
    |
116 |     ) -> Result<(Option<<C as Command>::ER>, bool), ProposeError> {
    |          ^^^^^^
    |
note: the lint level is defined here
   --> curp/src/lib.rs:41:5
    |
41  |     warnings, // treat all warnings as errors
    |     ^^^^^^^^
    = note: `#[deny(unknown_lints)]` implied by `#[deny(warnings)]`

error: unknown lint: `clippy::let_with_type_underscore`
   --> curp/src/client.rs:196:10
    |
196 |     ) -> Result<(<C as Command>::ASR, <C as Command>::ER), ProposeError> {
    |          ^^^^^^

error: could not compile `curp` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `curp` due to 2 previous errors
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phoenix500526** [comment]
Resolve in #334
